import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} `}>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
